//! The third-party notices (#73): the attribution document the installer
//! puts beside the application, read for Help ▸ Third-party notices.
//!
//! The document is generated by `tools/attribution` and bundled as a resource
//! by `tauri.conf.json`, so the text shown is the file that shipped, and
//! reading it needs no network. It is read here rather than imported into the
//! renderer's bundle so that there is one copy, on disk where a user — or a
//! licensor — can find it without starting the application.

use std::path::Path;

use tauri::Manager;

/// The document's name, in the resource directory and in the source tree.
pub const NOTICES_FILE: &str = "THIRD-PARTY-NOTICES.txt";

/// The attribution document as installed.
///
/// Asynchronous so that reading half a megabyte of text never happens on the
/// thread that runs the window.
///
/// # Errors
///
/// The resource directory is unknown, or the file cannot be read — a damaged
/// installation, which the dialog says in words.
#[tauri::command(async)]
#[allow(clippy::needless_pass_by_value)]
pub fn third_party_notices(app: tauri::AppHandle) -> Result<String, String> {
    let dir = app
        .path()
        .resource_dir()
        .map_err(|error| error.to_string())?;
    read_notices(&dir)
}

/// The notices in `dir`, or why they are not there.
fn read_notices(dir: &Path) -> Result<String, String> {
    let path = dir.join(NOTICES_FILE);
    std::fs::read_to_string(&path).map_err(|error| format!("{}: {error}", path.display()))
}

#[cfg(test)]
// In a test `expect` is the assertion. Same convention as `updater`.
#[allow(clippy::expect_used)]
mod tests {
    use super::*;

    /// The resource map in `tauri.conf.json` installs the document under
    /// this name; if either side changes alone, the dialog shows an error in
    /// every installed copy.
    #[test]
    fn the_bundle_installs_the_document_under_the_name_the_command_reads() {
        let config: serde_json::Value = serde_json::from_str(include_str!("../tauri.conf.json"))
            .expect("tauri.conf.json is JSON");
        let installed = config
            .pointer(&format!("/bundle/resources/{NOTICES_FILE}"))
            .and_then(serde_json::Value::as_str);
        assert_eq!(installed, Some(NOTICES_FILE));
    }

    #[test]
    fn the_committed_document_is_where_the_bundle_takes_it_from() {
        let text = read_notices(Path::new(env!("CARGO_MANIFEST_DIR"))).expect("read");
        assert!(text.starts_with(
            "==============================================================================\n\
             Blinkify: third-party notices\n"
        ));
    }

    #[test]
    fn a_missing_document_is_an_error_that_names_the_file() {
        let error = read_notices(Path::new("C:/nowhere")).expect_err("missing");
        assert!(error.contains(NOTICES_FILE), "{error}");
    }
}
