[package]
name = "blinkify-engine"
description = "The Blinkify media engine. Must not depend on Tauri."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
ts-rs = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
